### ISSUE TITLE
APK

### ISSUE THREAD

**Issue by xmha97** [mcatta/sleep#27]
How can I download this app?

**Comment by mcatta** [comment]
Hi @xmha97 , currently is still not available on the Play Store. I'm planning to do it in the next month, I need to prepare the soundtracks before the deployment.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by mcatta** [comment]
Hi @xmha97 , **Sleepify** is now live on the play store https://play.google.com/store/apps/details?id=dev.marcocattaneo.sleep

I'll add new tracks in the next weeks.

**Comment by xmha97** [comment]
Thanks but Google Play Store and F-Droid are blocked in my country.
Please upload the APK file to the GitHub release page.
Thanks 🙏

**Comment by mcatta** [comment]
You can find the latest apk here https://github.com/mcatta/sleep/releases/tag/v1.1.1 👍

**Comment by xmha97** [comment]
Why is it the ZIP file? You can upload the unarchived APK file.

**Comment by mcatta** [comment]
It's the artifact downloaded from the CI. I will publish directly the apk file in the next release.
